### ISSUE TITLE
Wiki images repository

### ISSUE THREAD

**Issue by X3msnake** [lexelby/inkstitch#119]
I started this issue to allow for fast image upload to use on the wiki

I know this might be somewhat unorthodox, but since i don't want to pollute the repo with the wiki images,  and since it is easy to copy paste a image into a issue here it goes.

If someone know a better and as fast as way as this let me know :)

here's the workflow if someone wants to adhere to it.

----
## Uploading a Image to this issue

1. Reply to this issue;

2.1 - For file images
- Just drag image driectly from your folder to the the issue text editor.

2.2 - For printscreens 
- Do a print screen
- Paste the clipboard memory into the the issue text editor.

3 - Copy the full link that appears on your text editor and use it as is on the wiki

This:

`![image](https://user-images.githubusercontent.com/11083514/37181642-c1afd9fa-2325-11e8-9bb8-d33c131711c3.png)`

Results on This:

![Inkstitch Embroider Menu](https://user-images.githubusercontent.com/11083514/37181642-c1afd9fa-2325-11e8-9bb8-d33c131711c3.png)

----
## Good Naming practices

It is good practice to change the text in the backets from 

`![image](https://user-images.githubusercontent.com/11083514/37182239-48f99e8a-2328-11e8-87c1-9ef667a71fdd.png)`

to a more detailed info about the picture

`![Satin Column Menu](https://user-images.githubusercontent.com/11083514/37182239-48f99e8a-2328-11e8-87c1-9ef667a71fdd.png)`

That is the text that the browser falls back if something goes wrong with loading the image. also what gets indexed in the seos or even serve as tooltips since it converts into alt
 
![alt text from markdown](https://user-images.githubusercontent.com/11083514/37182508-87ab3426-2329-11e8-86fd-92ea2371b380.png)

----

## Quick Tip 1: 
On windows you can select a window and press alt+prtscr and that will only copy the selected window

Like this;

![Embroider Menu Options](https://user-images.githubusercontent.com/11083514/37181862-9de696f2-2326-11e8-9a40-2761e666e911.png)
![Stroke Options](https://user-images.githubusercontent.com/11083514/37182016-4cb15c94-2327-11e8-97a6-69cd3ba8b927.png)

----
## Quick Tip 2: 

Use right click on a image posted by other member on this issue to copy the link directly with the option copy adress link

![right click copy link adress](https://user-images.githubusercontent.com/11083514/37182715-7adb255c-232a-11e8-80c6-785d7d589578.png)

----
## Quick Tip 3:

With the link adress on the clipboard memory you can add a image with the image icon by pasting the link in the image URL and adding the description text to Alt Text box

![adding image to wiki](https://user-images.githubusercontent.com/11083514/37183003-dd8df71e-232b-11e8-9b29-6c1e4e68b7f1.png)

**Comment by lexelby** [comment]
Neat idea. :)  Thanks for figuring this out.

**Comment by X3msnake** [comment]
Note: Satin Colum menu only works if your line weight is above 0.5mm, below that and it will still render a running stitch (Stroke)

![Satin Column Options](https://user-images.githubusercontent.com/11083514/37182239-48f99e8a-2328-11e8-87c1-9ef667a71fdd.png)

**Comment by LuPissarra** [comment]
teste:
![Teste](https://user-images.githubusercontent.com/25798726/37187826-fdc633e4-2343-11e8-93c4-7a73bdca0627.png)

**Comment by X3msnake** [comment]
Image for wiki FAQ - ilustrate how to find the installation path 

![image](https://user-images.githubusercontent.com/11083514/37572872-899a7de0-2b09-11e8-93ed-e4be6228c414.png)
