### ISSUE TITLE
Jump Stitch Created and Not Needed?

### ISSUE THREAD

**Issue by mrunion** [lexelby/inkstitch#128]
This may be my misunderstanding of how the software works, vs an actual issue, so bear with me. I am also new to embroidering -- we've only had our machine (a Brother PE-770) for less than a week.

When I create the embroidery file for my machine (a .PES or .PEC) using InkStitch, the software I use to open that file says it's corrupt. I also use SewArt and SewWhatPro from S and S Computing to create embroidery files. SewArt is an entry-level digitizer, and SewWhatPro can do lettering and stitch cleanup, etc.

Note: I can create a Janome file and it opens just fine in SewWhatPro (the colors are all wonky, but I can fix that). I have **not** tried to print one of the InkStitch-produced files directly.

I have attached screenshots of my current project SVG file to this email so you can review it. **This file is not for distribution because it uses a cartoon character I am testing with that I do not own.**

Another thing that I don't understand about the InkStitch-produced files is the jump stitch operation. I tested a two-color sample logo and created an embroidery file from InkStitch. The logo had a blob of blue on one site, and a blob of yellow on the other (it was the Python logo). The colors did not touch. InkStitch created the stitches for the blue blob, then switched to the yellow color for the yellow blob and had a yellow jump stitch from the blue blob to the yellow blob. The same logo created with SewArt didn't have the jump stitch between the colors because a color change took place anyway, it just moved the needle to where the yellow started and began stitching. Is this because I did something wrong (like not understanding STOP and TRIM), or because InkStitch just handles jump stitches/color changes differently.

You can see that same effect in the sample file I've attached. The pattern will have a color change, but will then just put a jump stitch in going to the next color. Look at the jump stitch on the left that goes from the border of the patch to the green shorts. If I had created this in SewArt, that color change from white to green would not require that jump stitch because the needle would just move over and start the new green color in it's starting place. (Again, this may be an educational item for me, not an issue with InkStitch.)

I can supply the sample SVG file if you want to send me a location to put it that's not publicly accessible. **It is using a well-known cartoon character I was testing with because that character is easy to draw**. This file is **not** intended for distribution, it was just something I was testing with.

Finally, my system info:

Arch Linux, latest updates (I do not run "testing" or pre-release code)
System 76 Oryx Pro, 16 GB RAM, nVidia 1070 GTX, KDE
Inkscape 0.92.2 2405546 2018-03-11
Brother PE-770 Embroidery Machine

![patch_sample](https://user-images.githubusercontent.com/5022458/37709408-7e1723c8-2ce0-11e8-9db9-c8b2ae681b09.png)

**Comment by wwderw** [comment]
> Arch Linux, latest updates (I do not run "testing" or pre-release code)
System 76 Oryx Pro, 16 GB RAM, nVidia 1070 GTX, KDE
Inkscape 0.92.2 2405546 2018-03-11
Brother PE-770 Embroidery Machine

What version of Ink/Stitch are you using?  I know you said that you don't use any testing or pre-release with Arch, but I don't know if that would apply to Ink/Stitch as well.

>Is this because I did something wrong (like not understanding STOP and TRIM)

Trim is for objects within the same color block that "you" don't want a jump stitch connecting to.  Should have no baring in this instance that I'm aware of if you used it or not.

**Comment by lexelby** [comment]
Thanks for the hugely detailed bug report!  From what you're describing, I think it is indeed a bug.  

We've got a PR going for print-to-pdf support that also has a pretty major reorganization of the stitch engine code.  I'm going to wait until after we merge that to take a look at this because it's possible that I fixed it along the way.

As to the PES not loading, I have no idea what that's about.  Perhaps a bug in libembroidery.  Or perhaps it doesn't like that extra jump stitch :)

**Comment by mrunion** [comment]
@wwderw Yikes, I forgot to include what version of InkStitch I was using: 1.4.0

@lexelby Thanks for the "thanks". As a developer myself I don't like brief "It doesn't work..." bug reports. And if there are code changes coming down the pipeline in an area that may affect this, I agree that holding off on investigating this any further is the right choice.

I will wait and test again after the PR is merged. Cleaning up those extra jump stitches is no biggie either. I've toyed with the idea of generating each piece of the design separately and then merging them in SewWhatPro. I might give that a whirl too.

Thanks again!

**Comment by mrunion** [comment]
I have an interest, yes. My day job and the few volunteer hours I do takes a lot of my time.

Let me wade a bit down in the code and see how well I understand it. I just might be able to help out bit.

**Comment by lexelby** [comment]
That's awesome!  Lack of time is definitely something I am familiar with.  No time commitment at all is expected it implied.

I'd recommend you go straight for the print-pdf branch rather than master.

**Comment by wwderw** [comment]
I apparently got the same result in one area of this design that I was working on to see about how to do fringe embroidery using the extension.

I got the unwanted thread jump as well and also this particular design results an exploding PES file (which could explain why @mrunion got an corruption error when opening it in another software, for reference this is issue #72).

I'll attached the SVG when I'm done testing how fringe handles with it in #72 thread.

CSV Output:

![csv output](https://user-images.githubusercontent.com/24878362/37795056-561e880a-2de1-11e8-9984-00746c7bb3b9.png)

DST Output:

![dst output](https://user-images.githubusercontent.com/24878362/37795061-5c9af808-2de1-11e8-8485-598568e42817.png)

PES Exploded Output:

![pes output](https://user-images.githubusercontent.com/24878362/37795077-66e5e57a-2de1-11e8-8bd8-e453344656d5.png)

It should also be noted that PEC format resulted in the same exploding file.  That was a direct conversion using libembroidery CLI tool from the CSV format to PEC format, so I'm thinking it is the library itself.

**Comment by lexelby** [comment]
@mrunion okay! Printing is merged into master now and v1.5.0 is released.  Would you be so kind as to email your svg over to inkstitch at lex.gd?

**Comment by lexelby** [comment]
@wwderw Do you still get the unwanted thread jump with this design in 1.5.0?  I didn't see it when I was debugging #72 but perhaps I did something differently.  Or maybe #127 fixed it?

**Comment by wwderw** [comment]
The JEF file format did produce one, but not the Brother formats.

**Comment by lexelby** [comment]
Interesting.  It looks like mrunion saw the extra jump even on the stitch preview in inkscape, so maybe this is two different issues.

BTW mrunion the corrupt PES is due to a bug in handing files with long file names.  As a workaround, try making the file name shorter than 16 characters.

**Comment by mrunion** [comment]
Sorry for the delay, guys. I will get the SVG to you, lex. I am sending it now....

**Comment by lexelby** [comment]
Thanks!  I tested it out, and I have some good news!  I'm quite confident that v1.5.0 fixed this particular extra jump stitch.  I don't see the problem in v1.5.0, but I definitely do see it when I install v1.4.0 and run it with that.

Thanks again for the awesome bug report, and thanks for sharing your SVG.  It's really cool to see how people use Ink/Stitch!
