### ISSUE TITLE
Manual Stitch missing first stitch (76f7bcd)

### ISSUE THREAD

**Issue by X3msnake** [lexelby/inkstitch#137]
![image](https://user-images.githubusercontent.com/11083514/38278990-42bca4cc-3796-11e8-9bba-87d7e3b71c60.png)

[ManualStitching.zip](https://github.com/lexelby/inkstitch/files/1873634/ManualStitching.zip)

**Comment by X3msnake** [comment]
![image](https://user-images.githubusercontent.com/11083514/38280026-f6646948-379a-11e8-8e72-ec9404e7d102.png)

Although the preview shows ok when you call embroider it does this :\

here's the new file
[ManualStitching2.zip](https://github.com/lexelby/inkstitch/files/1873742/ManualStitching2.zip)

**Comment by lexelby** [comment]
Thanks!  I'll take a look.  For problems with a pull request that hasn't been merged yet, you can just comment on the PR :) (#135)
