### ISSUE TITLE
Strange Error with Params on Latest Stable Release

### ISSUE THREAD

**Issue by wwderw** [lexelby/inkstitch#150]
Just got this error today when I was trying to take it for a spin today.

Using the latest stable version on Kubuntu 16.04.

![screenshot_20180418_152449](https://user-images.githubusercontent.com/24878362/38956330-d7c23b86-431c-11e8-9f40-1d5b98aeb937.png)

**Comment by wwderw** [comment]
Well, I bundled it in the AppImage itself and it worked.

I don't know why there is a permissions error with using the .config/inkscape/extensions locations as that's what I have been using all this time, but I bundled it within the AppImage itself and it works.

I'll just have to use the Windows VM to test any newer versions.

At least I go it to work again.

**Comment by lexelby** [comment]
Weird.  The error seems to be indicating that inkstitch/bin/embroider_params was not executable (or was not executable by you).  Perhaps you untarred it as root, or without permissions intact...?
