### ISSUE TITLE
Print PDF throws error when printing without specific palette defined

### ISSUE THREAD

**Issue by kaalleen** [lexelby/inkstitch#161]
Finally I tested the new inkstitch version (a little). Sorry, for taking so long!
I usually use no specific palettes - my machine wouldn't know about it anyway.
So I got this error when I started the print function:

> Traceback (most recent call last):
>   File "embroider_print.py", line 405, in <module>
>   File "inkscape-0.92.2/share/extensions/inkex.py", line 283, in affect
>   File "embroider_print.py", line 380, in effect
> AttributeError: 'NoneType' object has no attribute 'name'

pointing to this line in embroider_print.py: 

> selected_palette = palette.name,

So we need some kind of fallback if no palette name is defined?!?

**Comment by lexelby** [comment]
Oops!  Just a bug. I'll whip up a fix in a bit.
