### ISSUE TITLE
Don't Know if This is a Bug or Not....

### ISSUE THREAD

**Issue by wwderw** [lexelby/inkstitch#166]
I installed both the Linux and Windows (VM) version of 1.8 and I noticed that when going to the extensions > embroidery it shows 2 of my custom shortcut combos, but not the one for the Print portion.

You may or may not be able to see it in the center of the screen shot as it is faded from the extension, but it is still "known" in Inkscape, just not showing up in the extension itself.

It still works, I'm just thinking more of consistency, if this is a bug or if there is something else that I'm not doing.

Thoughts?  This only applies to the Windows version that I've noticed.

![shortcut](https://user-images.githubusercontent.com/24878362/40273801-3d533dbe-5b8d-11e8-8494-fb8f33ba1a66.png)

**Comment by lexelby** [comment]
I think this may be because I changed the extension's internal id for consistency.  If you assign a new shortcut does it stick?

**Comment by wwderw** [comment]
![shortcut 2](https://user-images.githubusercontent.com/24878362/40279675-3217fe24-5c0c-11e8-9154-976f0ac97745.png)

When I assigned a new one, it did show up, but it showed up under the previous assignment (I newly assigned ctrl + F12, but it shows the old one of ctrl + F11).  The new assignment works, it just doesn't show up correctly.

Even when nothing was showing up there, the shortcut still worked, it just didn't show up as a shortcut in the extension itself.

**Comment by lexelby** [comment]
Wow, I have no idea what's going on there.  I'm gonna have to blame Inkscape for this one, I guess.
