### ISSUE TITLE
Output plugins

### ISSUE THREAD

**Issue by lexelby** [lexelby/inkstitch#173]
Much like #26, implement a set of output plugins to allow "Save as" and "Save a copy as" directly to embroidery file formats like PES, DST, etc.  This solves the problem of #75, because "Save a copy" seems to always default to the directory where the SVG itself is.

The workflow would look like this:

1. Work on your SVG, saving periodically to `foo.svg`.
2. Use Embroider and Simulate to get everything the way you like it.
3. File -> Save a Copy
4. Name the copy `foo.pes` and select `Ink/Stitch - PES format`.
5. Make more changes, etc as your workflow dictates.
6. File -> Save a Copy
7. This time, `Ink/Stitch - PES format` will already be selected, since it's the last format you used.  You can reselect `foo.pes` and save over it.

This may feel more natural to users than having the extension save files in some directory.  It may also help with #169.

Level of effort: low.  What do people think, would this be useful?

**Comment by wwderw** [comment]
I would say go for it.

I agree that it would make more sense to have the save as for the embroidery output.  Makes it feel like Inkscape is more and more like a stand alone embroidery program in that regard.  Just a little more natural.

**Comment by X3msnake** [comment]
Interesting. So would this mean you would remove the dropdown embroider box then?

**Comment by lexelby** [comment]
The embroider extension?  Maybe!  I haven't decided yet. I probably wouldn't remove it entirely, just change it to "preview" because it shows you the stitch plan layer.

**Comment by X3msnake** [comment]
Cool, sounds great, go for it :)
