### ISSUE TITLE
Stack trace index error - while trying to set params in a non path object

### ISSUE THREAD

**Issue by X3msnake** [lexelby/inkstitch#186]
![image](https://user-images.githubusercontent.com/11083514/40893734-b347c034-679b-11e8-96d5-4b6eaf150738.png)

This error show up if you try to set params of a square object not converted to curves

Usually the params window shows up blank
![image](https://user-images.githubusercontent.com/11083514/40893760-159ec836-679c-11e8-907f-abd6f161d31b.png)

Now if you convert all to curves ctrl+shift+c 

![image](https://user-images.githubusercontent.com/11083514/40893793-681dbeb4-679c-11e8-80c4-06b766647530.png)

**Comment by lexelby** [comment]
I'm going to make Params show a useful error message like Embroider does, rather than show the blank window.
