### ISSUE TITLE
Folder/File Location on Window's Version

### ISSUE THREAD

**Issue by wwderw** [lexelby/inkstitch#191]
I don't know if this is related to my using the Binary Archive version of Inkscape or not, but I thought I would ask.

Where would the "inkstitch" folder that contains the preset and print setting json files be located, so that way I can transfer all my settings from one computer to the next?

I know where there are in Linux (.config folder), but I don't know where they are in the Windows system to put those files in my Windows VMs.

Where should I be looking?

**Comment by wwderw** [comment]
Never mind, I found it.

**Comment by lexelby** [comment]
For those who come here wondering what the answer is: in Inkscape, go to *Edit* -> *Preferences*, and choose *System*.  The path will be listed there (and you can configure it).
