### ISSUE TITLE
Printing on v1.10.0

### ISSUE THREAD

**Issue by readymotion** [lexelby/inkstitch#209]
Hey guys,
Been getting a button "choose file" on the print out. Not sure if it has to do with using a color palette now or the new update. Using google Chrome on Ubuntu
![ink stitch print preview](https://user-images.githubusercontent.com/24721785/41618882-9f62b81c-73c1-11e8-9240-6bc3beafe866.png)

**Comment by readymotion** [comment]
It does not show the button in Firefox.

**Comment by X3msnake** [comment]
@lexelby @kaalleen can you check this?

**Comment by wwderw** [comment]
I wonder where that is from.  The only thing that would have been close to that location is the ability to change the logo on the print out.

Now in Firefox there was a little shift of the text into the main InkStitch logo, but when I swap it out it isn't noticed (of course, I swapped it for more of a landscape logo, so I'm sure that helped in with that).

**Comment by lexelby** [comment]
It's the file picker for the icon, and it's supposed to be invisible!  Turns out I screwed up the css.  Interesting that it only shows up on some browsers.  I'll get a fix put together.

**Comment by readymotion** [comment]
Awesome thanks guys. 👍

**Comment by lexelby** [comment]
yay :D
