### ISSUE TITLE
Python-Issues on MacOS

### ISSUE THREAD

**Issue by ThomasRgbg** [lexelby/inkstitch#23]
Hi, 

using Inkscape and inkstich on MacOS caused my some trouble. Main issue is, with MacOS comes a historic python at /usr/bin. But many more advanced MacOS users install their tools via brew or Macports, which usually ends up getting a nice, up-to-date python installed, which supports pip and all other features. 
But this "good" python is in /usr/local/bin located. 

In some of the inkstitch scripts is the header fine to support this (embroider_params.py - "#!/usr/bin/env python"). 

While others use a hardcoded python path (embroider.py/embroider_update.py - "#!/usr/bin/python" or have no header (embroider_simulate.py). 

So I would recommend to use the env... header in all files. It is a simple change, so I think it is faster than using a pull-request. 

Kind regards, Thomas

**Comment by lexelby** [comment]
Thanks for the detailed bug report!  I really appreciate it.

Inkscape is... well, it has some "ideas" regarding its Python interpreter.  It actually invokes whatever Python interpreter it is configured to use and completely ignores the shebang!  I'm happy to change to the `#!/usr/bin/env python` shebang, for consistency, but that won't help you.  

On the flipside, you can configure which Python is used by modifying your Inkscape config, as described <a href="http://wiki.inkscape.org/wiki/index.php/Extension_Interpreters">here</a>.

My hope is to avoid the need for users to have to deal with that, though.  I just merged #16 which uses <a href="http://www.pyinstaller.org/">pyinstaller</a> to build a portable, packaged version of ink/stitch and all of its dependencies.  It packages its own Python in a way that gets around Inkscape's use of its choice of python interpreter.

I don't yet have an OS X build.  If you'd like to try to add an OS X build to the .travis.yml and test it out, I'd really appreciate a pull request.

**Comment by ThomasRgbg** [comment]
Thanks for the interpreter config in Inkscape, I did not found this by myself. So I did a bad hack instead... creating a symlink from /usr/local/bin/python to /Applications/Inkscape.app/Contents/Resources/bin/python. :-)

Maybe informative for other Mac users... building libembroidery-convert on Mac is pretty complicated, since you need qmake for it, which is part of the full QT package in brew etc. So for this simple tool you need a long list of dependencies to be installed. 

Luckily there is a prebuilt version in the Embroidmodder nightly build at https://github.com/Embroidermodder/nightly-ci, which works pretty well. 

I will have a look on the pyinstaller.

**Comment by lexelby** [comment]
If you're interested in taking on getting the Mac OS build working, it's over here: #36
