### ISSUE TITLE
Batch export to multiple embroidery formats

### ISSUE THREAD

**Issue by lexelby** [lexelby/inkstitch#25]
from @wwderw in #24:

> might want to think about a batch exporting function as well. When I do my stock designs, I usually have to save in Wilcom one at a time in the individual format.

**Comment by lexelby** [comment]
You know, I bet it'd be really cool if we implemented this as an output plugin.  You'd do File -> Save a Copy and select "Ink/Stitch batch export multiple formats (.zip)".  It'd pop up the settings dialog and you'd check the boxes for the format you want, and then bam, it gives you a zip file.  Then you can just add in a PDF printout of the operator detail view, and maybe a text file with the copyright or whatever, and your design is ready to post for sale!

**Comment by X3msnake** [comment]
Cool 
:) how hard is that?

**Comment by wwderw** [comment]
I like that idea as that is actually how I do things when I sell stock designs.

**Comment by lexelby** [comment]
> :) how hard is that?

Pretty easy, actually!  I might do it as part of #173.
