### ISSUE TITLE
Input plugin to directly open embroidery files

### ISSUE THREAD

**Issue by lexelby** [lexelby/inkstitch#26]
@wwderw, would it be useful to be able to File -> Open embroidery files?  Of course you'd only be able to edit them stitch by stitch, but you could move, resize (within reason) and add other inkstitch-supported objects to build on an existing design.

Is this a good idea, or not something you'd have much occasion to make use of?

**Comment by wwderw** [comment]
Yes, this would be a good idea for handling raw stitch files that I'm given from customers.  Sometimes it's for me to embroider, sometimes it's for me to fix the digitizing.

Personally, I get far more DST and PES files in this manner.  So I'm going to be selfish and say start with those 2, especially the DST format.

>resize (within reason)
+- 5% of the original size is what I typically suggest with a raw stitch file.  If it's something like a realistic animal etc, I would say less.

**Comment by lexelby** [comment]
Thanks, good to know that this would be useful.  I'm pretty sure this will be quick and easy to implement.

> Personally, I get far more DST and PES files in this manner. So I'm going to be selfish and say start with those 2, especially the DST format.

Now that I have libembroidery wired in, this would support all formats from the get-go. :)

**Comment by X3msnake** [comment]
This is closely related to #30

**Comment by lexelby** [comment]
implemented by #145
