### ISSUE TITLE
Tie-in and tie-off stitches

### ISSUE THREAD

**Issue by lexelby** [lexelby/inkstitch#28]
For home embroidery machines, we can kind of get away with no tie-in or tie-off stitches.  But for commercial embroidery with trimming and multiple needles, tie stitches are a must.  It'd be cool if the user could just check a box for tie-in and another for tie-off to have the tie stitches generated automatically.  Another option would be to automatically tie off after a TRIM and tie-in on the next object.

@wwderw How would you expect tie-in and tie-off to be generated by the software?  I'm thinking it could generate the stitch plan for the object first, then add tie-in or tie-off stitches after.  For tie-off, it could back-track along the stitch plan and then forward again.  For example, if you number the stitches for a 100-stitch object "... 97 98 99 100", then it could repeat the last couple: "... 97 98 99 100 99 98 99 100".  In fact, very early versions of the old inkscape-embroidery project did exactly this.

Another option would be to backtrack along the _direction_ of the stitch plan, but only go a set number of millimeters.  Is that preferable?

For tie-in we could just do the reverse of what we pick for tie-off.

**Comment by wwderw** [comment]
> Another option would be to automatically tie off after a TRIM and tie-in on the next object.

I would do this.  A tie in/off isn't going to be as necessary with a physical jump stitch as you are going to have that lock stitch already at the beginning and end of said jump stitch.

I would do about 3 stitches really close together.  Almost like a small bean stitch.  Tight grouping.  In fact, on some commercial software, if you set your small stitch filter a little too high, it will remove those.

**Comment by lexelby** [comment]
Sorry for the newb question, but what is a bean stitch?

**Comment by wwderw** [comment]
Bean stitch is the same as a back stitch.  A zig zag run stitch.  For a tie in/off, it would be a very compact zig zag stitch.

**Comment by lexelby** [comment]
> I would do this. A tie in/off isn't going to be as necessary with a physical jump stitch as you are going to have that lock stitch already at the beginning and end of said jump stitch.

Do machines automatically add tie in/off before and after a jump stitch?  What about at the start o a new color?

**Comment by wwderw** [comment]
No on both counts.

Tie in and off stitches are done within the software.  They are automated when using tools that generate satin, fill and/or run stitches.  Regardless of color, it just depends on if there is a connecting stitch before/after the object in question.

If we were to use manual stitches (poly lines in our case, which I think you mentioned Inkscape **can't do**), then we would have to manually add those in.  

They aren't needed before and after a jump stitch, but after a trim (either within the same color block or a change between color blocks).

**Comment by lexelby** [comment]
Wouldn't we still need to add tie in/off around a jump stitch so that the user can hand trim without it unraveling?

Are you saying that I should add tie-off before a color change even if the user didn't say "TRIM before"?  And I need to tie in for each new color?

I'm going to have to do some tests.  I _think_ I've observed my machine automatically adding tie-in for each new color, although I'm not sure.  Maybe that's a "training wheels" feature for entry-level home machines. :)

**Comment by wwderw** [comment]
> Wouldn't we still need to add tie in/off around a jump stitch so that the user can hand trim without it unraveling?

Yes, that is correct. 

> I'm going to have to do some tests. I think I've observed my machine automatically adding tie-in for each new color, although I'm not sure. Maybe that's a "training wheels" feature for entry-level home machines.

It may be up to the machine manufacturer as well.  I've had one brand that will do a tie in after a thread break has been "sensed" (either real or "imagined" thread break).

**Comment by lexelby** [comment]
Hah.  My machine just beeps at me in an accusatory fashion 10-20 stitches after the thread breaks and waits for me to rethread it.  Then there was the time that the thread got caught up coming off the spool and the needle broke, and my over-eager little machine continued ramming the stub through the fabric until I noticed...

**Comment by wwderw** [comment]
Oh yea, I've been there before.

**Comment by lexelby** [comment]
Alright, so, you said to do 3 stitches together, like a really tight bean-stitch.  So far I'm with you.  But where should I put them?  I don't want to go too far outside of where their design dictates, if any at all, for fear of my extra tie stitches being visible and looking wrong.

Let's say we're looking at tying off a running stitch that looks like this:

```
1       2       3       4       5       6       7
*-------*-------*-------*-------*-------*-------*
```

* is where needle penetrations happen, and let's say each - represents 0.1mm.  7 is where the line of running stitch ends and where I'm going to want to trim.

I could backtrack along the line toward 6, let's say 0.2mm:

```
1       2       3       4       5       6     8 7,9
*-------*-------*-------*-------*-------*-----*-*
```

Is that enough?  It seems to me like I've added two stitches, not three.  I could do it twice, so going back to 8 and forward to 9 again, for a total of 4 tie-off stitches.  Thoughts?

Another option is this:

```
                                             10 11
1       2       3       4       5       6   9 8 7
*-------*-------*-------*-------*-------*---*-*-*
```

In this example, I've gone back two stitches and forward 2.  This seems to be what is happening in one of your examples from when we were trying to figure out STOP and TRIM in DST files.  In that file, your running stitch was about 2.5mm apart, and wilcom backtracked _exactly_ 1.0mm per stitch, so 2mm total.  Perhaps I should follow their lead?

In that case, the question I have is, what do I do with something like this:

```
     2
     *
    / \
---*   *
   1   3
```

Let's say the distance between 2 and 3 is half a millimeter.  Obviously, if I backtrack 1mm from 3 in the direction of 2, I'd go way off the end of the point!  But if I just naively traveled 1mm back along the stitch path, I'd go from 3 directly to 1, and I'd be putting thread between 1 and 3 where it doesn't belong.

Maybe the answer here is to try to go back 1mm, but if I encounter a stitch, stop there.  So in this case, I'd go from 3 back to 2, back to 1, forward to 2, and forward to 3.

Does that sound good?

Of course, for tie-in, I'll just reverse the process; the same rules apply.

In any case, what I mean to say is, damn this stuff is complicated ;)

Oh, one more thing: what about a satin?  Let's say I'm ending a 2mm-wide satin.  If I follow the above rules, I'd put a needle penetration in the center between the satin.  Is that going to look weird?  Or will it be okay because it's way at the end of the satin?  It might be useful for me to see what kind of DST file wilcom produces for a 2mm-wide satin with a TRIM right at the end.

**Comment by wwderw** [comment]
The best way that I could think of to illustrate this is how Thred does it.  It's easier to visually see.

![knots](https://user-images.githubusercontent.com/24878362/36079486-f7019a12-0f48-11e8-8dd2-ae6b6f4fa352.PNG)

The 5 boxes that follow the angle of what one would think to be the first stitch stitch is how they do the tie in (just repeat the process for tie off).  It goes back and forth in the same shape/angle of the satin stitching, so it doesn't look out of place.

The square slightly off to the left side that doesn't have the horizontal bar in the center is actually the first node point, disregard that for this discussion.

**Comment by lexelby** [comment]
For reference, how wide is the satin in that Thred example?

**Comment by wwderw** [comment]
> For reference, how wide is the satin in that Thred example?

1.75mm or .068"

For anything that's below .04" or ~1mm, I'll make a run stitch.

The run stitch uses the same method, but have to be careful as it may create a bulge that is more noticeable.  Not always good to have the start/end point right on top of each other when a tie in/tie off is used.
