### ISSUE TITLE
Simulation to Work with Stitch Formats?

### ISSUE THREAD

**Issue by wwderw** [lexelby/inkstitch#37]
Right now, the Simulate version of the extension only seems to work with the CSV format.

Since the addition of libembroidery convert directly to the extension, I would imagine the CSV format in most instances (other then for testing/debugging of functions in stitch files) would be skipped in place for machine files.

Is it possible to have Simulate run a simulation of say a DST, PES file etc?

**Comment by lexelby** [comment]
Whoops!  That's a bug.  It's certainly possible to get it to run for all formats.  I'll fix it when I get a chance, but until then, just running Params without anything selected will show a full simulation.

**Comment by wwderw** [comment]
>but until then, just running Params without anything selected will show a full simulation.

Not getting a full simulation with this one.

Now, if I move the triangle to the first position instead of the satin column, I might get both the triangle and the satin column, but not the run stitch.

If I do the satin column first (which is how I digitized it and how I left it in the file), I'll just get the satin column.

[Test.zip](https://github.com/lexelby/inkstitch/files/1664990/Test.zip)

**Comment by lexelby** [comment]
Huh!  I'll have to dig into that.

**Comment by wwderw** [comment]
What I'm getting.


[Simulation.zip](https://github.com/lexelby/inkstitch/files/1665048/Simulation.zip)
