### ISSUE TITLE
Inset option for fill underlay

### ISSUE THREAD

**Issue by wwderw** [lexelby/inkstitch#39]
What about an inset option for fill underlay like the one that is implemented for the satin column?

Some fill shapes are "complex" enough that the underlay may peak through.  Or have to drastically make the stitch length smaller on the top stitch, so it can flush out those more complex shapes, which can lead to very dense stitching.

Thoughts?

**Comment by lexelby** [comment]
Totally doable!

I generally do satin around my fill, at least in part to deal with this kind of issue.  Is it common to have a fill without satin around it?

**Comment by wwderw** [comment]
> I generally do satin around my fill, at least in part to deal with this kind of issue. Is it common to have a fill without satin around it?

Ideally, you would want a satin around it as it helps give the piece a finished look as well as help seal in those edges of the fill.

However, it does depend on the size and shape.  Sometimes when I do blends, I don't have edges around it.  If I'm doing realist embroidery like this

![example](https://user-images.githubusercontent.com/24878362/35467161-cbd5be9c-02d0-11e8-90a3-30746f7bd584.png)

I won't have outlines around it.  It just depends on the design and application.

**Comment by lexelby** [comment]
Got it!  Thanks, that's a great example.
