### ISSUE TITLE
Error installing Shapely

### ISSUE THREAD

**Issue by ncp1113** [lexelby/inkstitch#53]
I tried getting this to run on my little raspberrypi because of my difficulty running it on my Mac. I got an error installing Shapely. Here is the output:
pip install -r requirements.txt 
Downloading/unpacking backports.functools-lru-cache (from -r requirements.txt (line 1))
  Downloading backports.functools_lru_cache-1.4-py2.py3-none-any.whl
Downloading/unpacking wxPython (from -r requirements.txt (line 2))
  Downloading wxPython-4.0.1.tar.gz (67.9MB): 67.9MB downloaded
  Running setup.py (path:/tmp/pip-build-2D4GjI/wxPython/setup.py) egg_info for package wxPython
    
    no previously-included directories found matching 'docs/sphinx/build'
    warning: no previously-included files matching '.git' found under directory 'wx'
    warning: no previously-included files matching '*.pyc' found under directory 'wx'
    warning: no previously-included files matching '__pycache__' found under directory 'wx'
Downloading/unpacking networkx (from -r requirements.txt (line 3))
  Downloading networkx-2.1.zip (1.6MB): 1.6MB downloaded
  Running setup.py (path:/tmp/pip-build-2D4GjI/networkx/setup.py) egg_info for package networkx
    
    warning: no files found matching '*.html' under directory 'doc'
    warning: no files found matching '*.css' under directory 'doc'
    warning: no previously-included files matching '*~' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '.svn' found anywhere in distribution
    no previously-included directories found matching 'doc/build'
    no previously-included directories found matching 'doc/auto_examples'
    no previously-included directories found matching 'doc/modules'
    no previously-included directories found matching 'doc/reference/generated'
    no previously-included directories found matching 'doc/reference/algorithms/generated'
    no previously-included directories found matching 'doc/reference/classes/generated'
    no previously-included directories found matching 'doc/reference/readwrite/generated'
Downloading/unpacking shapely (from -r requirements.txt (line 4))
  Downloading Shapely-1.6.4.post1.tar.gz (224kB): 224kB downloaded
  Running setup.py (path:/tmp/pip-build-2D4GjI/shapely/setup.py) egg_info for package shapely
    Failed `CDLL(libgeos_c.so.1)`
    Failed `CDLL(libgeos_c.so)`
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-2D4GjI/shapely/setup.py", line 80, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "shapely/_buildcfg.py", line 167, in <module>
        fallbacks=['libgeos_c.so.1', 'libgeos_c.so'])
      File "shapely/_buildcfg.py", line 161, in load_dll
        libname, fallbacks or []))
    OSError: Could not find library geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so']
    Complete output from command python setup.py egg_info:
    Failed `CDLL(libgeos_c.so.1)`

Failed `CDLL(libgeos_c.so)`

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-2D4GjI/shapely/setup.py", line 80, in <module>

    from shapely._buildcfg import geos_version_string, geos_version, \

  File "shapely/_buildcfg.py", line 167, in <module>

    fallbacks=['libgeos_c.so.1', 'libgeos_c.so'])

  File "shapely/_buildcfg.py", line 161, in load_dll

    libname, fallbacks or []))

OSError: Could not find library geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so']

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-2D4GjI/shapely
Storing debug log for failure in /home/pi/.pip/pip.log

**Comment by X3msnake** [comment]
If you want a shortcut you can try this Virtual image i made for VirtualBox

https://drive.google.com/drive/folders/1QsVOYLsdRA0SXFxdIMb9nRu1L1o4y5oq

**Comment by X3msnake** [comment]
@ncp1113 

did you try the VM?

Raspberry py is 32bit if it was a 64bit arm it would work with DietPi and the travis cibuild of inkstitch since it is a 64 bit compile and it is similar to the image i'm using for the VM.

OrangePi PC is a good and low cost solution for this. I will try to set up a OPi with this and report back if it worked or failed ;)

**Comment by lexelby** [comment]
This is due to an oddity of how Shapely handles its DLLs.  I don't think it really makes sense for us to handle Shapely installation issues in this project, especially since we now have the VM and portable linux and windows builds, and hopefully soon a Mac one as well.
