### ISSUE TITLE
inkstitch/bin/share/icons and themes ?

### ISSUE THREAD

**Issue by AkiraNorthstar** [lexelby/inkstitch#64]
I don't know if this before 1.2.0:
institch/bin/share/icons and institch/bin/share/themes packaged in the last release.
Is that what we want, or is it an accident?

**Comment by lexelby** [comment]
Yes, that's purposeful.  It's necessary to ensure that the Params dialog looks right.  Is it causing a problem?

I actually had to jump through a lot of hoops to make pyinstaller package those directories in.

**Comment by AkiraNorthstar** [comment]
No, no problem with these files, i just wondering about shipping the icons and themes.

**Comment by lexelby** [comment]
Yeah, gtk won't render apps correctly without any theme and basic icons -- I found that out the hard way.
