### ISSUE TITLE
Error messages are no longer displayed?

### ISSUE THREAD

**Issue by AkiraNorthstar** [lexelby/inkstitch#73]
Since we have l10n support, error messages are no longer displayed.
If a Object/Path has different number of nodes, nothing happens.
Even if I change inkscape to english.
Can anyone confirm this?

**Comment by lexelby** [comment]
Hmm, I wasn't able to reproduce this problem -- I still see the error messages (in English, anyway).  Anyone else seeing this problem?

**Comment by AkiraNorthstar** [comment]
After reinstall fedora27, changing system and inkscape language it is the same as above.
Even if i force an error (satin collum + one node more in a subpath), nothing will displayed.
Are umlauts completely supported in inkstitch?
I will test again, please do not close this thread

**Comment by AkiraNorthstar** [comment]
It's possible that this is the problem:
message.po
```
303 #: inkstitch.py:94
304 #, python-format
305 msgid "parseLengthWithUnits: unknown unit %s"
306 msgstr "AnalysiereLängeMitEinheiten: Unbekannte Einheit %s"
```

**Comment by X3msnake** [comment]
@AkiraNorthstar 

Have you tested this issue on the new release 

I think this was fixed already

**Comment by lexelby** [comment]
I think this has been fixed.  If not, please reopen.
