### ISSUE TITLE
Make Embroider Directory same as saved file location

### ISSUE THREAD

**Issue by wwderw** [lexelby/inkstitch#75]
I was wondering, is there anyway that default directory saved is where the SVG file is also saved?  The extension would just know based on where the SVG is saved (now of course, that would mean that the SVG would have to be saved first before any file could be exported, at least I would imagine that would be the case).

Right now from what I can tell it's either saving to the extension directory (if no destination is listed for the Directory) or have to manually set it each and every time.

It also looks like to me that simulate requires the exported file to be in the same directory as the SVG in order to properly work.  I think it would help in that regard as well.

Thoughts?

**Comment by lexelby** [comment]
Unfortunately, this is one of those few things that just aren't possible.  Open up an SVG saved by inkscape and you'll see why.  Near the top, the file name is there (sodipodi:docname) but not the folder.  The extension only has access to the svg contents, so it has no way of knowing what folder it's in :(

Maybe there's some kind of trick or hack to figure it out, but I haven't found it yet.

**Comment by wwderw** [comment]
> Maybe there's some kind of trick or hack to figure it out, but I haven't found it yet.

What about how Inkscape knows where to export files to PNG format?  It seems to auto populate that option.

**Comment by wwderw** [comment]
Darn Inkscape for that.  Oh well, it's easy enough to move from the home directory to where the SVG file is.

**Comment by wwderw** [comment]
> You wrote a comment about how inkscape knows where to export PNG files, but I think you deleted it. 

I did, because while I did test my theory and within various file folders to change things up.  Those initial (positive) tests were just in the Home directory.  Big problem there is that most of my files are not stored in the Home directory, but in their respective directories among several NAS devices.

Once I tried things out on the NAS, that's when I realized that it really didn't work like I thought it did.  It appears that it remembers the last used file path when exporting.

That's what prompted me to change my post.

**Comment by lexelby** [comment]
Oh.  Darn. :(

**Comment by lexelby** [comment]
Perhaps if we filed a feature request with Inkscape to store the full path inside the SVG, then we could update Inkstitch to read that.  Anyone want to file that feature request?

**Comment by X3msnake** [comment]
@lexelby 

If you store the location inside SVG won't this mean if you move the file manually the location will be wrong? 

how does inkscape know where the file is at the moment? it must know otherwise you would not be able to hit save without having a popup window show up for you to choose the location no?

**Comment by lexelby** [comment]
> If you store the location inside SVG won't this mean if you move the file manually the location will be wrong?

When Inkscape runs an extension, it saves a temporary SVG file and then gives it to the extension program.  Inkscape would be saving the path into the SVG immediately before Inkstitch sees it, so there wouldn't be any risk of the user manually moving it.

> how does inkscape know where the file is at the moment? it must know otherwise you would not be able to hit save without having a popup window show up for you to choose the location no?

Sure, it knows.  It just doesn't tell Inkstitch. :(

**Comment by X3msnake** [comment]
Okok, I got it now :), thanks for the clarification. gonna pop up in the inkscape github and post a reference to this issue see what they have to say ;)

**Comment by X3msnake** [comment]
mmm, they use gitlab and don't have issues, guess it must be in the forum? :/

**Comment by X3msnake** [comment]
Done

https://answers.launchpad.net/inkscape/+question/664831

**Comment by X3msnake** [comment]
update:

> 
> Yes, this is correct. There already exists a bug report for it here:
> https://bugs.launchpad.net/inkscape/+bug/1359471
> 
> You could add a comment explaining why it's needed for Inkstitch.
> 
> I'm not sure about the mentioned security reasons, though - what exactly they were.
> Was it just about having the file name included in the file? Then the solution would be to tell an extension which file it is currently working on.
> If that already poses a security risk, then, I guess it's not going to happen.
> 
> You could try to find out more about the security concerns people had.

**Comment by X3msnake** [comment]
There used to contain a variable that stored the full path on the svg, it was removed for security reasons

> sodipodi:docbase="C:\complete path to the file.............."
> If I put a file made with Inkscape online, this is a major privacy concern,
> I don't want people to see the structure of my hard disk. 
> Could this be changed, or at least obscured, as an option?

https://bugs.launchpad.net/inkscape/+bug/168958

Unless they decide to add a internal cached reference that allows extensions to see where the file is at this will not happen. Inkscape is a slow mamuth when it comes to some areas of the development for what i read in the forum. things linger for years

**Comment by lexelby** [comment]
Ah, I see the problem.  Darn. :(
