### ISSUE TITLE
Stitch as is option? *FEATURE REQUEST*

### ISSUE THREAD

**Issue by X3msnake** [lexelby/inkstitch#82]
When we hit embroider, the generated onscreen paths is what is being sent to the machine file right?

Would it be possible to have a stitch as is option, where the points were exported as they are draw?

Would it be possible to use the preview layer manually tweek the Stitches and then use this new embroid-as-is check box?

**Comment by lexelby** [comment]
Yup.  Great ideas here, and I believe they're all captured in this: https://github.com/lexelby/inkstitch/issues/30

**Comment by X3msnake** [comment]
Cool
