### ISSUE TITLE
Pressing apply in Params before simulate window shows up crashes inkscape

### ISSUE THREAD

**Issue by lexelby** [lexelby/inkstitch#92]
Discovered by @X3msnake in #83.  The Inkscape crash may be specific to Windows, but there's probably a stack trace or similar on other platforms.

**Comment by X3msnake** [comment]
It gave me a bunch of info that i could not record because once i tried to reproduce it again i was unable to do it. If anyone else catches it please add the info here. Sorry

**Comment by X3msnake** [comment]
I think this is solved on release 1.5.0 #127
