### ISSUE TITLE
DST output mishandles stitches longer than 12.1mm

### ISSUE THREAD

**Issue by lexelby** [lexelby/inkstitch#99]
DST format can't encode a single stitch or jump that would move the needle more than 12.1mm in the X or Y axis.  libembroidery complains about such stitches but doesn't actually do anything to fix them.

The solution is to add a set of JUMPs before the actual stitch to bridge the gap.  It's probably also a good idea to see if any other formats impose similar limitations, especially if they're smaller.

**Comment by X3msnake** [comment]
True it was one of the first things i read when i started investigating about open source embroidery last year is a documented "feature" in the DST format, legacy from the puch cards era

> This is based on an old paper tape format, thread colour is not usually stored in the file. At each thread change stop, the thread colour has to be found in an external source; the embroidery machine usually gives needle number or stitch count at each stop.
> Several jump stitches may be run together to span distances greater than 12.1 mm, the following normal stitch is the start of the next run of stitches (don't draw a line from the last move stitch to the following normal stitch).

https://community.kde.org/Projects/Liberty/File_Formats/Tajima_Ternary

**Comment by lexelby** [comment]
Of course, if it takes 3 JUMPs or more to span the distance, then machines will treat that as a TRIM.  I'm pretty sure there's no way to jump more than 36.3mm without the machine trimming.  I can't see why that would be undesirable, though.

**Comment by wwderw** [comment]
The longer the stitch length is, the slower the machine has to go when it's crossing that huge expanse and that runs the risk of getting a machine out of time.

This is more of a concern with big patterns on multi-needle machines and even with bridge style machines, especially when driven by a step motor versus a servo motor.

Most commercial software will not work around this.  They safe way around this is to turn off trims at the machine.  Now that means all trims are ignored, even ones that you may want.

The main time that I turn off trims is when doing puff and I'm trying to keep everything satin stitches and there are areas that are greater then 12 mm.

**Comment by lexelby** [comment]
Ah, interesting context, thank you.  I didn't realize turning off trims was possible.

What does it mean for a machine to "get out of time"?

**Comment by wwderw** [comment]
> What does it mean for a machine to "get out of time"?

One of the most common issues that come about with getting out of time is needles start hitting the bobbin case.  Timing isn't in sync.

**Comment by lexelby** [comment]
I was wrong, it looks like libembroidery already breaks up long stitches automatically.
